theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul

title: 광야에서 혼자 중얼거리는 소리
tagline: 블로그
description: >-
  광야에서 혼자 중얼거리는 소리입니다. 침례 요한은 아니지만, 말씀을 연구하고 시대를 향한 하나님의 말씀을 작게나마 나눠보고자 합니다.

url: "https://murmuringjohn.github.io"

github:
  username: murmuringjohn

social:
  email: murmuringjohn@gmail.com
  links:
    - https://github.com/murmuringjohn
    # 다른 SNS는 필요하면 추가하세요
